version: 2
jobs:
  test:
    docker:
      - image: java:openjdk-8-jdk
        environment:
          TZ: "/usr/share/zoneinfo/Asia/Tokyo"
    steps:
      - checkout
      - run: chmod +x ./gradlew # Grant execution permission
      - run: ./gradlew test
      - store_artifacts:
          name: store_artifacts
          path: build/reports
          destination: artifacts
      - store_test_results:
          name: store_test_results
          path: build/test-results
          destination: artifacts
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
